### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by releaf** [sblundy/webpack-dev-server-intellij-plugin#1]
When I follow the instructions and import this into IntelliJ 2016.1.3 I get the following message:
![image](https://cloud.githubusercontent.com/assets/4107042/19855697/49cdc1f8-9f4c-11e6-9366-63497aaa4bd3.png)

**Comment by sblundy** [comment]
At this point, you'll need to build it. `gradlew build` should compile and build it. The prepared plugin will be at `WebpackDevServer/build/distributions/WebpackDevServer.zip`. Let me know if this doesn't work for you.

I'll add a section on the README

**Comment by releaf** [comment]
Thanks, that all worked. One snag I ran into was that I my JAVA_HOME was pointed at 1.7. Once I pointed to 1.8 it built successfully and the install worked properly.
